### ISSUE TITLE
Erro 500 ao cadastrar uma interação com Anexo (ref planilha - Envio de pedido como usuário) Marina

### ISSUE THREAD

**Issue by studiocuboweb** [Transparencia-Brasil/achados-e-pedidos-site#11]
Problema adicionado por Marina [na planilha de ajustes da homologação azure](https://docs.google.com/spreadsheets/d/1iFNm9-nnPB1AGra5bbEpTQOuFGHABOG1KCbk9Eyq2R0/edit?ts=60ad22db#gid=420871920)

**Tópico:** 

Envio de pedido como usuário

**Descrição:**

No cadastro de outra interação depois da resposta (recurso de 1ª instância com inclusão de anexo), apareceu erro 500, mas a interação foi registrada e o anexo, upado.

**Problema:**

o arquivo src/Model/Entity/PedidoAnexo.php responsável por salvar os arquivos estava chamando um método que era obrigatório a passagem de um parâmetro (repare que o () está vazio).

````
$pedidoAnexo->ES_AtualizarInserirAnexosPorPedido();
`````

Então quando não tinha anexo o sistema funcionava, mas quando um anexo era adicionado o sistema retornava erro 500 pq estava esperando esse parâmetro no metodo.

**Solução:**

Adicionado null ao método para passar um parâmetro vazio:

````
$pedidoAnexo->ES_AtualizarInserirAnexosPorPedido(null);
````

**Teste:**

Para testar é necessário criar um novo pedido com interação e anexo.

1. [se logar / criar um novo cadastro](http://transparencia-achados.azurewebsites.net/minhaconta/login/logar)
2. clicar em inserir pedido
3. selecionar ou criar um novo agente público
4. preencher o formulário do pedido
5. preencher o formulário da interação
5.1. Anexar pelo menos um arquivo

**Commit:**

https://github.com/Transparencia-Brasil/achados-e-pedidos-site/commit/79a07409e03eed41d9f7d0055ce8dcdadaf71308

**Ticket Trello**
[162# [migracao-azure] AEP: Envio de pedido como usuário - fix criação de interacao com anexo](https://trello.com/c/cF2b4wCd/162-162-migracao-azure-aep-envio-de-pedido-como-usu%C3%A1rio-fix-cria%C3%A7%C3%A3o-de-interacao-com-anexo)

**Comment by studiocuboweb** [comment]
@rdurl0 @JnCoe @mgaldino 

Mais um item [da planilha Aba Outros testes](https://docs.google.com/spreadsheets/d/1iFNm9-nnPB1AGra5bbEpTQOuFGHABOG1KCbk9Eyq2R0/edit?ts=60ad22db#gid=420871920)

Tópico: Envio de pedido como usuário

Favor testar. se estiver tudo certo, favor fechar o issue

**Comment by maiatoji** [comment]
A inclusão de agente funcionou, assim como a inclusão de anexo a um pedido. Mas o pedido não apareceu na página /pedidos passados cinco minutos após inclusão e aprovação na moderação.

**Comment by maiatoji** [comment]
Tudo certo. Não sei como fechar issue

![image](https://user-images.githubusercontent.com/80543612/122479450-7ab07100-cfa1-11eb-9b1b-8805e7d4f3ec.png)

**Comment by studiocuboweb** [comment]
@maiatoji só clicar no botão Close Close issues (conforme imagem) 
![Screen Shot 2021-06-18 at 10 49 14](https://user-images.githubusercontent.com/32527574/122571248-e7b81b00-d022-11eb-8a69-07ff04f98520.png)


Fechando o ticket

**Comment by maiatoji** [comment]
Não aparecia pra mim :-/
(Mas tudo bem, não importa agora 😆)
