### ISSUE TITLE
Não é possível cadastrar novo agente público (no caso de o agente público não ser encontrado na primeira etapa do envio de pedido pelo usuário).

### ISSUE THREAD

**Issue by studiocuboweb** [Transparencia-Brasil/achados-e-pedidos-site#12]
Problema adicionado por Marina [na planilha de ajustes da homologação azure](https://docs.google.com/spreadsheets/d/1iFNm9-nnPB1AGra5bbEpTQOuFGHABOG1KCbk9Eyq2R0/edit?ts=60ad22db#gid=420871920)

**Tópico:** 

Envio de pedido como usuário

**Descrição:**

Não é possível cadastrar novo agente público (no caso de o agente público não ser encontrado na primeira etapa do envio de pedido pelo usuário).

**Problema:**

Quando logado, ao clicar no Inserir Pedido e cadastrar um novo órgão publico clicando na frase:

Clique aqui caso não tenha encontrado o órgão público.

No campo "insira o órgão publico superior" não aparece as opções de autocomplete conforme digitação impossibilitando a escolha e o cadastro de um novo órgão no campo "Insira o nome do Órgão Público ao qual fez o pedido".

Esse bug foi observado quando não se navega em https. 

Quando se navega com o site em HTTP, ele faz uma requisição ajax (background) usando HTTPS e causa problema de CORS (conforme imagem anexada)
![Screen Shot 2021-06-10 at 20 41 36](https://user-images.githubusercontent.com/32527574/121610391-4df1dc00-ca2c-11eb-9461-569500946dfa.png)

**Solução:**

Criei um issue #13 para o Will tentar forçar o HTTPS. Se não, quando publicar esse problema será corrigido.

**Teste:**

Para testar é necessário criar um novo pedido se certificando que o endereço está utilizando o HTTPS.

1. [se logar / criar um novo cadastro](http://transparencia-achados.azurewebsites.net/minhaconta/login/logar)
2. clicar em inserir pedido
3. selecionar um novo agente público (verificar se o navegador está utilizando HTTPS)

Se ao digitar no campo "insira o órgão publico superior", o sistema está funcionando corretamente

**Commit:**

Não tem commit.

**Ticket Trello**
[163# [migracao-azure] AEP: Envio de pedido como usuário - fix cadastro de órgãos públicos. forçar https no htaccess](https://trello.com/c/JmClaF4E/163-163-migracao-azure-aep-envio-de-pedido-como-usu%C3%A1rio-fix-cadastro-de-%C3%B3rg%C3%A3os-p%C3%BAblicos-for%C3%A7ar-https-no-htaccess)

**Comment by studiocuboweb** [comment]
@JnCoe @rdurl0 @mgaldino 
Agora o sistema força redirecionamento http para https. 

O fluxo de cadastro de novo órgão publico está funcionando.

Favor testar. Se estiver tudo Ok pode fechar o ticket

**Comment by maiatoji** [comment]
Está tudo ok. Eu não sei como fechar o issue
![image](https://user-images.githubusercontent.com/80543612/122479059-dfb79700-cfa0-11eb-80c4-2473421200be.png)
