### ISSUE TITLE
Caracteres/acentos desconfigurados

### ISSUE THREAD

**Issue by maiatoji** [Transparencia-Brasil/achados-e-pedidos-site#18]
Oi, @pauloeducampos! (cc @andremotasc)

O Achados está com os acentos zoados, acho que deu algum chabu na codificação da linguagem... Pode dar uma olhada, por favor?

É uma questão interessante: não aparece na lista de pedidos nem nos menus, mas acontece nas páginas dos pedidos, como [este](https://achadosepedidos.org.br/pedidos/historico-de-contratacao-de-brigadistas-204838)...

<img src="https://user-images.githubusercontent.com/80543612/127207372-cee2e109-301d-45c7-9f7e-44f067fff370.png" width="500">

... Na [área de notícias](https://www.achadosepedidos.org.br/na-midia/conselho-da-amazonia-nao-explica-valor-arrecadado-pela-operacao-verde-brasil-2-em-2020)...

<img src="https://user-images.githubusercontent.com/80543612/127207843-ef417cf7-49f2-4a1d-ad57-0b5978975ca1.png" width="500">

... E na [área de publicações](https://www.achadosepedidos.org.br/publicacoes)

**Comment by wgnann** [comment]
o mysql da azure mudou o encoding padrão para ISO-8859-1.

o que deve acontecer é:

1. a conexão é realizada (mas o cakephp meramente IGNORA a configuração de encoding);
2. os dados são pedidos;
3. os dados em UTF-8 são exibidos como LATIN1;
4. deu ruim.

talvez seja necessário atualizar o `vendor/cakephp/cakephp/src/Database/Driver/Mysql.php` e adicionar no braço, mais ou menos na linha 70, o `SET NAMES utf8`.

exemplo: `PDO::MYSQL_ATTR_INIT_COMMAND => "SET NAMES utf8"`

**Comment by studiocuboweb** [comment]
@wgnann tentei PDO::MYSQL_ATTR_INIT_COMMAND => "SET NAMES utf8" conforme sua orientação não deu certo... Não tem como voltar a configuração dos bancos do azure para utf8?

Até as queries dos graficos pararam de funcionar em /dados que são acessadas tipo essa rota que retornava um json agora uma tela em branco pq da problema de encode:
https://www.achadosepedidos.org.br/api/atendimentoPedidosPorAnoETipo

**Comment by wgnann** [comment]
Fiz um deploy de teste com a sugestão aqui, https://testadosepedidos.azurewebsites.net/dados, e pareceu funcionar. De qualquer forma, acho que consegui colocar o `SET NAMES` dentro do MySQL da Azure.

Sobre o transparencia.org.br, já havia aberto um issue lá por se tratar de um problema sistêmico. A mudança surtiu efeito lá, mas no achados talvez seja necessário corrigir algumas coisas porque o input tem cara de ter ido com o encoding errado.

Atento que o blog não padeceu do mesmo problema.

**Comment by maiatoji** [comment]
O Achados está certinho de novo, obrigada. De fato, o texto publicado mais recentemente na seção "Notícias" precisará ser colocado de novo no encoding certo, mas em 5 minutos resolvo :).
