### ISSUE TITLE
Lista de órgãos públicos não aparece na hora de inserir pedidos

### ISSUE THREAD

**Issue by maiatoji** [Transparencia-Brasil/achados-e-pedidos-site#19]
Olá, @pauloeducampos e @andremotasc 

Mais um chabuzinho: na hora de inserir um pedido pelo método tradicional (interface do usuário logado), a lista de órgãos públicos não está carregando no primeiro passo do fluxo:

![image](https://user-images.githubusercontent.com/80543612/127547860-48ffe4c2-9a2a-42b2-92fc-1119a259bc36.png)

Deveria ser assim:

<img src="https://user-images.githubusercontent.com/80543612/127547895-1169f2c1-73a7-4f9c-b0d9-2db7611e5c78.png" width="500">

**Comment by studiocuboweb** [comment]
@maiatoji este problema está relacionado com o encode do banco de dados.
Agora que ele foi resolvido, eu consegui fazer o Fundaç funcionar no filtro. veja imagem em anexo
![Screen Shot 2021-07-30 at 12 06 27](https://user-images.githubusercontent.com/32527574/127673335-566fd55c-577a-4d7b-ac63-bd020104b1d2.png)


Poderia verificar tb e já fechar esse issue?

obrigado

**Comment by maiatoji** [comment]
Corrigido! Obrigada :)
