### ISSUE TITLE
Encode gerou problema na visualização de pedidos que foram inseridos durante o problema no banco e refletiu na visualização dos dados

### ISSUE THREAD

**Issue by studiocuboweb** [Transparencia-Brasil/achados-e-pedidos-site#20]
Quando o Azure mudou o encode do banco de dados e o problema aconteceu, novos registros de pedidos foram inseridos. Estes registros entraram com problema de encode e por isso vão continuar com problema mesmo após a correção do Will (SET NAME utf8) aplicada (acompanhado nesse [issue.](https://github.com/Transparencia-Brasil/achados-e-pedidos-site/issues/18).

Ex de pedido com problema de encode:
https://achadosepedidos.org.br/pedidos/calendario-escolar-2020-e-2021--contexto-da-pandemia-

Por isso, [na página de dados](https://achadosepedidos.org.br/dados), um endpoint específico faz o fetch dos dados do mysql, mas não consegue fazer o json_encode por conta de problemas de caracter.

Gráfico que não aparece:
Classificações de atendimento por ano

endpoint retorna tela em branco
https://www.achadosepedidos.org.br/api/atendimentoPedidosPorAnoETipo

No Model
src/Model/Entity/Dados.php
````
        $atendimentoPedidosPorAno_arr = $connection->execute($query)->fetchAll('assoc');
        // $totalPedidos = $totalPedido_array[0]["total"];
        return json_encode($atendimentoPedidosPorAno_arr);
````

**Comment by studiocuboweb** [comment]
@rdurl0 e @maiatoji precisamos encontrar esses pedidos inseridos durante o problema de encode (se realmente houve, mas me parece que sim por conta do exemplo de pedido que eu colquei na descrição).

Vocês chegaram a inserir pedidos em julho, certo? Foram muitos? Conseguimos apagar e recadastrar novamente?

**Comment by maiatoji** [comment]
Uai, dei uma olhada aqui nos pedidos de julho e só esse estava bugado. Corrigi na mão mesmo, porque é curtinho.

Os que eu e outros usuários subimos em julho e estavam bugados voltaram ao normal depois da solução do problema de encode.

**Comment by studiocuboweb** [comment]
Ok. de qualquer forma, alguma registro com problema de encode / ou view
ainda está travando o gráfico em questão.
estamos verificando esse problema. vamos manter esse issue aberto até ser
resolvido

**Comment by studiocuboweb** [comment]
Problema com o gráfico Classificações de atendimento por ano [na página Dados](https://www.achadosepedidos.org.br/dados).

Definitivamente estava com problema por conta do encode errado, mas ao debugar a página eu deixei comentada uma linha do código. descomentei a linha e o gráfico agora está aparecendo.

fechando o issue
