### ISSUE TITLE
Não tem o diretório config, nem o app.php

### ISSUE THREAD

**Issue by wgnann** [Transparencia-Brasil/achados-e-pedidos-site#3]
Ele está no `.gitignore`.

**Comment by studiocuboweb** [comment]
@wgnann retirada a pasta /config do gitignore.

Apareceram vários arquivos de plugins e vendors além dos tradicionais arquivos de configuração da app em /config então quando vc der o git pull virão vários arquivos.

**Comment by wgnann** [comment]
Funcionou.
