### ISSUE TITLE
Pedidos não são listados em /pedidos

### ISSUE THREAD

**Issue by maiatoji** [Transparencia-Brasil/achados-e-pedidos-site#33]
Olá, @studiocuboweb e @wgnann 

Há dias, os pedidos não são listados/carregados na página /pedidos. Poderiam dar uma olhada, por gentileza?

Obrigada.

**Comment by studiocuboweb** [comment]
@maiatoji dessa vez não foi queda do elastic search.

Suspeito que foi criada uma regra no cloudflare para forçar todas as URLS do domínio achadosepedidos.org.br a usarem https no lugar do http

![Screen Shot 2021-11-22 at 18 48 12](https://user-images.githubusercontent.com/32527574/142940237-09f6c01d-0d6e-47c2-bab2-9a3d05d3d802.png)

A hospedagem GoogleCloud que usa o endereço endp.achadosepedidos.org.br não estava configurada para receber acessos HTTPS:

1. Não possuía um certificado HTTPS de origem instalado
2. Não possuía no servidor web / apache um virtual host para atender as requisições https com o certificado de origem instalado
3. O firewall do Google Cloud não aceitava acessos a porta 443 (que é a porta específica para o HTTPS)

Apenas para deixar documentado.

1. Criei um novo certificado de origem no Cloudflare para atender o endereço endp.achadosepedidos.org.br e instalei os arquivos .pem e .key na pasta /etc/ssl-keys/endp.achadosepedidos.org.br/

![Screen Shot 2021-11-22 at 18 52 53](https://user-images.githubusercontent.com/32527574/142941290-2b9f6898-bdd3-4174-8867-1e2157dc8dae.png)

2. Criei um novo arquivo vhost em /etc/apache2/sites-enabled
endp.achadosepedidos.org.br-ssl.conf

3. Configurei o firewall para aceitar conexões na porta 443.

Testei a página https://www.achadosepedidos.org.br/pedidos e agora os pedidos estão sendo listados.

Favor testar e se estiver tudo certo fechar esse issue.
