### ISSUE TITLE
Limite de 'post' no upload de anexos

### ISSUE THREAD

**Issue by maiatoji** [Transparencia-Brasil/achados-e-pedidos-site#35]
Olá, @wgnann

Estou tendo problemas para subir anexos no Achados. 

Ao fazer o login de usuário e cadastrar a resposta a [este pedido](https://achadosepedidos.org.br/pedidos/comunicacoes-entre-embaixadas-na-alemanha-e-noruega), por exemplo, eu só consegui subir oito arquivos. Quando tento subir outro, nada acontece (nem mensagem de erro). O @studiocuboweb comentou que pode ser o limite de 'post' atual. Você pode dar uma olhada, por favor?

Obrigada

**Comment by wgnann** [comment]
É possível, sim. Deixei uma modificação - fora do repositório - que aumenta os limites de arquivo de 2 para 20MB e de post de 8 para 32MB.

**Comment by maiatoji** [comment]
Funcionou! Obrigada, Will.
