### ISSUE TITLE
 Exibição de classificação de atendimento na página de pedidos

### ISSUE THREAD

**Issue by rdurl0** [Transparencia-Brasil/achados-e-pedidos-site#45]
1. **Mouseover próximo à lupa e o texto de status de atendimento (indicar o local com um ponto de interrogação como [este](https://github.com/Transparencia-Brasil/achados-e-pedidos-site/blob/master/webroot/assets/images/pedidos/pergunta.png)) com o seguinte texto e redirecionamento para link (também no texto):** 
    - > "Esta classificação é feita com um modelo de inteligência artificial que analisa a estrutura dos textos do pedido e da resposta para determinar se a solicitação foi atendida de fato, ou seja, se a informação foi fornecida. O código, desenvolvido especialmente para o Achados e Pedidos, tem acurácia de 84,6%. Caso encontre uma classificação incorreta, por favor nos notifique. Saiba mais [aqui](https://www.achadosepedidos.org.br/na-midia/achados-e-pedidos-usa-inteligencia-artificial-para-classificar-atendimento-a-pedidos)"

 2. **Reordenamento da coluna à direita do pedido (ver figura abaixo), onde se vê os boxes "0 Seguidores > Avaliação > Encontrou algo errado"  reordenar para "Encontrou algo errado > Avaliação > 0 Seguidores"**
    - > ![image](https://user-images.githubusercontent.com/22898231/175122152-a66fc5c0-f7fc-4293-bc5c-69b4d7ce259d.png)

4. **Remover o (Status verificado) **
    - > ![image](https://user-images.githubusercontent.com/22898231/175122343-df4989ae-33e7-4ebb-b461-2216208bda4d.png)
    - > Queremos retirar esse campo em destaque, mantendo somente o status de atendimento + ponto de interrogação com mouseover;

**Comment by studiocuboweb** [comment]
@rdurl0 conforme autorizado pelo whatsapp, está publicado! favor testar.

Abraço

**Comment by studiocuboweb** [comment]
@rdurl0 eu havia optado e inclusive comentei no email que ia fazer clique no lugar do mouseover por dois motivos:
1. Mouseover não funciona bem no mobile
2. O comportamento mouseover para o tooltip não pressupõe que existe um link ou algo dentro da mensagem.
O que acontece: O evento do mouseover fica no ponto de interrogação. se vc sair do ponto de ? para clicar no link "aqui" o popup irá fechar antes da pessoa conseguir clicar no link. 

Mesmo assim, se vocês quiserem que o comportamento seja o mouseover, vou precisar quebrar aqui a cabeça para ver como fazer. Então só confirmar. Quer que eu veja como funciona no mouseover ou seguimos com o clique?

Uma opção é colocar um delay para o pop fechar sozinho com um atraso (depois do mouseleave)

E esse print eu entendo que você clicou em vários ? e não fechou nenhum, confere?
Se for esse o caso, eu vou aplicar um ajuste para que, caso vc clique no botão 1, abrir o poup e não fechar, clicar no botão 2 o popup 1 fecha e o 2 abre.

Fico no aguardo sobre a questão do mouseover e me confirme se o print está relacionado com essa questão.

**Comment by studiocuboweb** [comment]
@rdurl0 acabei de publicar em produção o ajuste. favor validar.

Me avisa se posso fechar o ticket?

Abraço

**Comment by rdurl0** [comment]
Obrigado, Paulo! Podemos fechar essa issue! ✅
