### ISSUE TITLE
Exibição de classificação de atendimento na página de dados com novos gráficos

### ISSUE THREAD

**Issue by rdurl0** [Transparencia-Brasil/achados-e-pedidos-site#46]
@rdurl0 : criar visualizações com R

**Comment by studiocuboweb** [comment]
@rdurl0 essa atividade está ligada com essa página: https://transparencia-brasil.github.io/pagina-de-dados-AeP/dashboard-guide-v2.html e esse repositório https://github.com/Transparencia-Brasil/pagina-de-dados-AeP (confere?)

Acabei de colocar aqui na máquina local as 3 visões Atendido, Não atendido e Parcialmente Atendido, conforme print:
![Screen Shot 2022-08-03 at 12 51 49](https://user-images.githubusercontent.com/32527574/182654019-9979aa7c-cf10-4df2-83c4-40bb8970cebb.png)


É isso mesmo? Vai manter as visões Total Pedidos, Respondidos e Não respondidos ou é para substituir?

obs: Caso vamos manter todas as visões, eu vou precisar arrumar os icones do Atendido, Não atendido e parcialmente.

**Comment by rdurl0** [comment]
Paulo, na minha opinião podemos ficar somente com os pedidos classificados e tirar as taxas de resposta. Vou checar com a equipe e te passo o encaminhamento dessa parte, ok?

**Comment by studiocuboweb** [comment]
@rdurl0 eu retirei a taxa de resposta e coloquei o gráfico da taxa de atendimento por ano conforme print:
![Screen Shot 2022-08-23 at 21 27 58](https://user-images.githubusercontent.com/32527574/186289110-82c8369e-476a-4981-97bb-77793bc578e8.png)


Só pedi para colocar a % no eixo y. Mas a imagem está coerente com a query, confere?

**Comment by rdurl0** [comment]
@pauloeducampos acho que faltou algo na query que é a exclusão de pedidos não classificados. Basicamente o que precisa fazer é incluir um filtro na query com `having Ativo = 1 and NomeStatusPedido != 'Não Classificado'`

A query no banco de dados deve ficar assim:
```
select p.Ativo,
        count(p.Codigo) as QuantidadePedido,
        year(p.DataEnvio) as AnoEnvio,
        sp.Nome as NomeStatusPedido
  from pedidos as p
  left join status_pedido as sp on (p.CodigoStatusPedido = sp.Codigo)
  group by sp.Nome, year(p.DataEnvio)
  having Ativo = 1 and NomeStatusPedido != 'Não Classificado' // <-------------------------------- AQUI !
  ;
```

Excluindo pedidos não classificados e recalculando os percentuais os pedidos ficarão mais ou menos assim:
![image](https://user-images.githubusercontent.com/22898231/187769207-d268aee0-40c3-48e9-93c9-171d4b9ead24.png)

**Comment by rdurl0** [comment]
@pauloeducampos , segue nossa lista de ajustes com base no PDF que vc nos mandou:

- O texto da primeira seção tem que ser alterado:  *"Veja a taxa de atendimento dos pedidos de acesso à informação cadastrados no Achados e Pedidos. A classificação é feita com um modelo de inteligência artificial que analisa a estrutura dos textos do pedido e da resposta para determinar se a solicitação foi atendida de fato, ou seja, se a informação foi fornecida. O código, desenvolvido especialmente para o Achados e Pedidos, classifica corretamente os pedidos em 85% dos casos. Saiba mais [aqui](https://achadosepedidos.org.br/na-midia/achados-e-pedidos-usa-inteligencia-artificial-para-classificar-atendimento-a-pedidos)*
- O que aconteceu com os ícones originais dos cards de "Atendido"/ "Não atendido"/"Parcialmente atendido"?
- No gráfico de linhas: os rótulos dos dados serão exibidos ao passar o mouse em cima?
- No gráfico de linhas: precisa aumentar a fonte do eixo x (mesmo tamanho do eixo y)
- Está sobrando um título "Taxa de atendimento por ano" abaixo do gráfico de linhas
- Mapa: trocar o título por "Atendimento a pedidos"
- Qual é a visualização do mapa que está sendo exibida no PDF? Não dá para ver quais filtros estão aplicados. Era ideal que pudéssemos navegar para ver como os filtros estão funcionando. O mapa e/ou as barras devem exibir as informações que estão aparecendo na caixa de seleção.
- Precisa alterar o texto de exibição dos dados na lateral esquerda inferior do mapa para *"xxxx pedidos foram atendidos/não atendidos/parcialmente atendidos etc."*

**Comment by rdurl0** [comment]
Essa versão no stage ficou boa para validação, mas ainda temos melhorias para fazer, principalmente no mapa. Seguem ajustes necessários:

>  No gráfico de linhas: precisa aumentar a fonte do eixo x (mesmo tamanho do eixo y)

O tamanho da fonte está bom mas o eixo X está com enquadramento errado, pois as linhas terminam antes do ano de 2022 - pode checar a posição da linha em relação ao eixo x? 

> No gráfico de linhas: os rótulos dos dados serão exibidos ao passar o mouse em cima?
> paulo: está pendente. Ainda não conseguimos colocar os rótulos.

Ficamos no aguardo da introdução dos rótulos também.
 

> Qual é a visualização do mapa que está sendo exibida no PDF? Não dá para ver quais filtros estão aplicados. Era ideal que pudéssemos navegar para ver como os filtros estão funcionando. O mapa e/ou as barras devem exibir as informações que estão aparecendo na caixa de seleção.
> paulo: Validar

 O Mapa ainda está bastante confuso, não está claro qual é a informação que está exibida no mapa, no texto e nas barras.
 Talvez seja importante validar esses agrupamentos juntos, podemos marcar um horário se quiser (terça ou quarta são bons dias para mim).
  As caixas de seleção, quando vazias (ex: Nível Federativo = "--"), não devem exibir dado nenhum. 
  Por default podemos manter a caixa de seleção com os valores: Nível Federativo = "Federal", Esfera = "Executivo", Atendimento = "Atendido".
  E quando os pedidos são da esfera Federal, os dados não podem ser disponibilizados por UF, o ideal é o mapa ficar cinza (sem dados, com aspecto de "desativado").

> O que aconteceu com os ícones originais dos cards de "Atendido"/ "Não atendido"/"Parcialmente atendido"?
> paulo: Validar

OK!

> Está sobrando um título "Taxa de atendimento por ano" abaixo do gráfico de linhas
> paulo: Validar

OK!

> Mapa: trocar o título por "Atendimento a pedidos"
> paulo: Validar

OK!

> Precisa alterar o texto de exibição dos dados na lateral esquerda inferior do mapa para "xxxx pedidos foram atendidos/não atendidos/parcialmente atendidos etc." 
> paulo: Validar

OK!

**Comment by rdurl0** [comment]
Ainda temos pendentes aqui o enquadramento dos eixos do gráfico de linhas e a implementação dos rótulos/mouseover no mesmo plot.

Sobre o mapa, andei revisando a query e vi que os números batem, mas ainda temos algumas correções, que seguem:

- Escala de cores
- Texto com resumo dos dados
- Texto com resumo dos dados

Abaixo um detalhamento dos tópicos, eu melhorei a [simulação do dashboard](https://rdurl0.shinyapps.io/achados-e-pedidos-dados/) com mais números para ajudar validar os resultados.

**Escala de cores:** 
- As cores no mapa não correspondem às cores da legenda. Tanto SP como PR deveriam ser da mesma cor, que é a da faixa dos 40%, correto?
> ![image](https://user-images.githubusercontent.com/22898231/191616504-68351847-0877-4a6a-b917-effd6b4125d5.png)

**Texto com resumo dos dados:**
- Quando o Nível Federativo NÃO é federal, o texto NÃO deve ser exibido, pois os dados são das UF's e, portanto, independentes entre si.
> ![image](https://user-images.githubusercontent.com/22898231/191616577-8513d724-f976-49d0-b9c3-581cfd8ca8ec.png)

- O número acima deve ser descartado, o que afeta outros filtros, pois aparentemente ele está somando na figura abaixo e apresentando dados errados para Nivel Federativo = "Federal"
   - Esfera: Federal    | Poder: Executivo | Status: Atendido | 70.245 pedidos [CORRETO - MANTER]
   - Esfera: Estadual  | Poder: Executivo | Status: Atendido |   1.348 pedidos [ERRADO - REMOVER]
   - Esfera: Municipal | Poder: Executivo | Status: Atendido |   7.635 pedidos [ERRADO - REMOVER]
   - Total: 70.245 + 1.348 + 7.635 = 79.228
> ![image](https://user-images.githubusercontent.com/22898231/191616644-f2240051-fa44-41d3-9fdc-f6bd12da7c0d.png)

**Texto com resumo dos dados:**
Conversando com a Marina, achamos melhor exibir o total de pedidos junto com o texto, por exemplo:
> "Brasil< br>
> 70.245 pedidos< br>
>  foram atendidos,< br>
>  47,5% do total de pedidos cadastrados< br>
>  para esta seleção (147.783)." 
> `[usar vírgula na casa decimal de % e ponto no separador de milhar, <br> é só para demonstrar a quebra de linha]`

**Comment by studiocuboweb** [comment]
Oi Raul, 

**O que está feito para validação mo [stage](https://stage.achadosepedidos.org.br/dados)**
1. Escala de cores
2. Texto com resumo dos dados Legenda Brasil deve aparecer apenas para Federal: Está corrigido, favor validar
3. Número total de pedidos
4. Novo texto para legenda. Não consegui utilizar a sua quebra de texto recomendada com <br>. Ficou estranho.

**O que está pendente:**
1. Formato dos números (usar vírgula na casa decimal de % e ponto no separador de milhar, <br> é só para demonstrar a quebra de linha). Vou precisar alterar em toda a página:
- card antendido (ponto no separador do milhar)
- card antendido (procentagem com ,)
- card não antendido (ponto no separador do milhar)
- card não antendido (procentagem com ,)
- card parcialmente antendido (ponto no separador do milhar)
- card nparcialmente antendido (procentagem com ,)
- Mapa Atendimento a pedidos: mouseover gráfico de barras (ponto no separador do milhar)
- Mapa Atendimento a pedidos: número de pedidos (ponto no separador do milhar)
- Mapa Atendimento a pedidos: % de pedidos (procentagem com ,)
- Mapa Atendimento a pedidos: total de pedidos para a seleção (ponto no separador do milhar)
- card Tempo médio da resposta ao pedido inicial (com , vírgula)
- card Pedidos respondidos em até 20 dias: % de pedidos (procentagem com ,)
- Gráfico Quanto tempo leva para um pedido ser respondido: tooltip número total de pedidos (ponto no separador do milhar)
2. Colocar rótulo / tooltip mouseover no gráfico Classificação de atendimento por ano

Dúvida:
O que seria enquadramento dos eixos do gráfico de linhas?

Para o tooltip (item 1) eu passei para meu especialista e aproveitei para passar esse formato dos números e % (item 2).

Vamos levar até 10 dias para resolver essas duas pendências.

Fico no aguardo da sua validação

**Comment by rdurl0** [comment]
> O que seria enquadramento dos eixos do gráfico de linhas

A posição dos valores no eixo-x não bate com a posição dos "pontos" no grafico de linhas
![image](https://user-images.githubusercontent.com/22898231/191816792-27d2992b-81a4-4e15-87ee-0256459200bb.png)

O correto seria este alinhamento entre eixo-x e pontos aos longo da linha:
![image](https://user-images.githubusercontent.com/22898231/191816983-2ac47c0a-fadc-457e-ad1b-5a83b1a8e319.png)

**Comment by rdurl0** [comment]
Outro ponto importante é a legenda do mapa, precisa alterar o texto do título e o texto das legendas, conforme imagem (o quadradinho com a cor pode manter o que já está):
![image](https://user-images.githubusercontent.com/22898231/191817875-86fbab1e-4264-4922-b5e1-cc5da6cbce2c.png)

**Comment by studiocuboweb** [comment]
@rdurl0 

Seguem os últimos ajustes pendentes que publiquei no [stage](https://stage.achadosepedidos.org.br/dados) para você validar:

1. Formato dos números (usar vírgula na casa decimal de % e ponto no separador de milhar, é só para demonstrar a quebra de linha). Vou precisar alterar em toda a página.
2. Colocar rótulo / tooltip mouseover no gráfico Classificação de atendimento por ano
3. Enquadramento dos eixos do gráfico de linhas?
4. Legenda do mapa

Fico no aguardo do seu retorno. Falta mais alguma coisa?

**Comment by maiatoji** [comment]
Boa tarde, Paulo

Dois ajustes ainda necessários, por favor: 

1) No mouseover do gráfico de linhas, exibir entre parênteses a porcentagem relativa a cada classe, na frente dos valores nominais (exemplo ilustrativo na imagem)

![linhasaep](https://user-images.githubusercontent.com/80543612/193889161-0563cad9-7279-4ad4-9f53-7cdfe71442c4.jpg)


2) No mapa: no filtro "nível federativo", se "Municipal" estiver selecionado e "Judiciário" ou "Ministério Público" forem selecionados no filtro "esfera de poder", o mapa deve ficar em branco (como nos casos federais) e a legenda dinâmica (no canto inferior esquerdo do mapa) deve exibir o texto "Não existe Judiciário Municipal" e "Não existe Ministério Público Municipal", respectivamente.

**Comment by studiocuboweb** [comment]
Oi @maiatoji os dois itens estão feitos. Favor validar no https://stage.achadosepedidos.org.br/dados

fico no aguardo.

**Comment by maiatoji** [comment]
Pode colocar em produção por favor, @studiocuboweb.

**Comment by studiocuboweb** [comment]
@maiatoji está publicado em produção.
Favor validar. Posso fechar o issue e ticket?
