### ISSUE TITLE
Testes front end - feito internamente pela TB

### ISSUE THREAD

**Issue by rdurl0** [Transparencia-Brasil/achados-e-pedidos-site#5]
Elaboramos [um documento](https://docs.google.com/document/d/1NR77heyoEuaFrqlg5XUtOtgoRpm8J3n_6WYJtxwVPDs/edit) com a descrição do teste e [uma planilha](https://docs.google.com/spreadsheets/d/1iFNm9-nnPB1AGra5bbEpTQOuFGHABOG1KCbk9Eyq2R0/edit#gid=0) para reportar os resultados do teste.

Testes ainda estão pendentes:

- [ ] Publicação de notícia
- [ ] Envio de pedido como usuário
- [ ] envio de pedido via importador (csv) (verificar se requer implementação do importador)
- [ ] Carregar imagens, carrossel ou banner
- [ ] Testar interações de usuário (seguir, moderar pedido, marcar atendimento, etc.)

**Comment by studiocuboweb** [comment]
@rdurl0 @maiatoji creio que todos esses itens já estão OK, confere?

Pode fechar esse issue?
