### ISSUE TITLE
Remover seção "Confira os dados"  e  "Órgãos com mais pedidos atendidos e negados" da home

### ISSUE THREAD

**Issue by rdurl0** [Transparencia-Brasil/achados-e-pedidos-site#56]
Remover as seções:

* "Órgãos com mais pedidos atendidos e negados" 
![image](https://user-images.githubusercontent.com/22898231/191623568-c145d087-59ad-4368-88a3-0ae61b40b5ad.png)

* "Confira os dados" 
![image](https://user-images.githubusercontent.com/22898231/191623641-7c3aa611-696a-4dfd-a865-c15e6669eb64.png)

**Comment by studiocuboweb** [comment]
Oi Raul, está feito. favor validar

https://stage.achadosepedidos.org.br/
