### ISSUE TITLE
erro 500 em /dados

### ISSUE THREAD

**Issue by wgnann** [Transparencia-Brasil/achados-e-pedidos-site#6]
O banco de dados está sugerido _hardcoded_ como `tblai` em vez de usar o que estiver configurado no `config/app.php`.

Exemplo: https://github.com/Transparencia-Brasil/achados-e-pedidos-site/blob/41b920f99ae7d02846b22c133bf6698e3e4b3930/src/Model/Entity/Dados.php#L37

**Comment by studiocuboweb** [comment]
@wgnann Feito.
Apaguei o nome da tabela hardcoded e a página agora está funcionando

commit: https://github.com/Transparencia-Brasil/achados-e-pedidos-site/commit/7e9d9a4b903b262b03990e9524984c76c53751f4


vou fechar o ticket
