### ISSUE TITLE
[URGENTE] Erro 500 na inserção de pedidos

### ISSUE THREAD

**Issue by maiatoji** [Transparencia-Brasil/achados-e-pedidos-site#60]
Oi, @studiocuboweb 

Por favor, veja esta questão com prioridade.

Quando um usuário completa o fluxo de inserção de um pedido, o site fica um tempão carregando e retorna uma página de "Erro 500". Apesar disso, o pedido é inserido na base. Ou seja, o usuário é levado a acreditar que o processo deu errado e tende a duplicar/triplicar a inserção de pedido.

Isso se reflete também na moderação dos pedidos no admin: o sistema indica "erro interno. Tente novamente mais tarde", mas quando damos "refresh" na página de moderação, o pedido foi aprovado/reprovado.

**Comment by studiocuboweb** [comment]
Oi Marina, bom dia.

Copiei o Marcelo que vai nos ajudar a debugar esse problema. Te mantenho
informada.

Abraço

**Comment by studiocuboweb** [comment]
@maiatoji me parece que vocês mudaram a senha do email abaixo:

MAIL_HOST: smtp.gmail.com
USER: no-reply@transparencia.org.br

Poderiam me passar a nova?

O que acontece:
1. O usuário faz o cadastro de um pedido
2. Clica no botão salvar
3. O dado é registrado na base
4. Email de aviso é disparado
5. Erro "Senha do email está invalida"

**Comment by maiatoji** [comment]
Oi, @studiocuboweb, [aqui](https://share.1password.com/s#NujrWITW4Qwj4CgNk7PzMnUGGpMh6HCIJL2GaBOUAac) você pode ver a senha. O link expira em 7 dias.

**Comment by studiocuboweb** [comment]
@maiatoji Essa senha é do login do gmail da conta no-reply (e ok).
Acontece que a senha utilizada é a app password, que permite você criar senhas específicas para cada uso (ex: smtp achados e pedidos). Com essa senha eu consigo disparar email pelo site, mas não consigo me logar na conta do gmail.
Antes dela, a senha do gmail ficava no código expondo o login para os programadores do projeto, causando falha de segurança.

Para ter essa opção ativa, preciso ativar o fator de autenticação dupla (que estava desativado).

Então o que eu fiz:
1. ativei o fator de autenticação dupla para o meu celular
2. gerei um app password para disparar email no achados e pedidos
3. configurei essa nova senha na azure.

![Screen Shot 2022-10-19 at 18 01 59](https://user-images.githubusercontent.com/32527574/196804319-8d25549f-0d0e-428d-ac16-cb606e3c02b9.png)

Consegui disparar um email de esqueci a senha conforme print:

![Screen Shot 2022-10-19 at 18 05 11](https://user-images.githubusercontent.com/32527574/196804326-29aca777-b270-47d4-a010-0a275029888a.png)

![Screen Shot 2022-10-19 at 18 05 32](https://user-images.githubusercontent.com/32527574/196804332-0d46a8e5-6404-4142-b8ca-5056084a8428.png)

favor testar no fluxo de cadastro só por desencargo. Me avisa se posso fechar o ticket?

obs: Se o duplo fator de autenticação for desabilitado, essa app password tb será deletada e vai dar problema no site novamente...

**Comment by maiatoji** [comment]
**Acho** que entendi. Testei o "esqueci minha senha" e a inserção de um novo pedido e deu certo! Obrigada.

Por algum motivo, perdi seu telefone; pode me passar de novo?

**Comment by studiocuboweb** [comment]
Passei o telefone por email. Fechando o ticket
