### ISSUE TITLE
275# [achadosepedidos] Revisão da query de criação de um anexo no ES. (lentidão para subir pedidos com anexos)

### ISSUE THREAD

**Issue by studiocuboweb** [Transparencia-Brasil/achados-e-pedidos-site#63]
**Problema descrito**
Ao percorrer o fluxo de cadastro de um pedido pelo site, e na criação de uma interação subir um anexo, o sistema fica lento e ocasionalmente retorna timeout do nginx.

**Diagnóstico** 

O problema não está no upload do arquivo, mas na query que pega os dados do banco mysql para criar o registro do anexo no elasticsearch ([exemplo de registro criado](https://endp.achadosepedidos.org.br/api/anexos/consultar/158764)). 

Se entrar no admin e subir uma publicação com anexo, o sistema executa com uma relativa velocidade (oq prova que o upload está OK).

O fluxo é:
1. Se logar no site
2. Cadastrar um pedido (escolhendo o órgão publico)
3. Cadastrar uma resposta (anexando um arquivo)

O sistema faz o seguinte:
1. Salva a resposta na tabela pedidos_interacoes
2. Salva os dados do arquivo na tabela pedidos_anexos
3. Salva o arquivo no disco / bucket
4. Executa a sincronização com o ES 
4.1. Pega o registro do anexo no banco de dados (tabela pedidos_anexos) (QUERY LENTA)
4.2. Envia os dados para o ES através do endpoint anexos/gravar/$CodigoDoAnexo

Query com problema
````
Select pa.Codigo anexos_codigo, pa.Arquivo anexos_arquivo, "" anexos_conteudo_arquivo, pi.Codigo interacoes_codigo, pi.Descricao interacoes_descricao, DATE_FORMAT(pi.DataResposta,"%Y-%m-%d") interacoes_data_resposta,a.Codigo pedidos_codigo,a.CodigoUsuario usuarios_codigo,c.Nome usuarios_nome,c.Nome usuarios_slug,c.Email usuarios_email,d.Codigo agentes_codigo,d.Nome agentes_nome,d.Nome agentes_slug,h.Codigo tipo_pedido_origem_codigo,h.Nome tipo_pedido_origem_nome,a.CodigoTipoPedidoSituacao tipo_pedido_situacao_codigo,g.Nome tipo_pedido_situacao_nome,a.CodigoStatusPedido status_pedido_codigo,e.Nome status_pedido_nome,f.Codigo status_pedido_interno_codigo,f.Nome status_pedido_interno_nome,tpr.Codigo tipo_pedidos_resposta_codigo,tpr.Nome tipo_pedido_origem_nome,tp.Codigo tipo_poder_codigo,tp.Nome tipo_poder_nome,tnf.Codigo tipo_nivel_federativo_codigo,tnf.Nome tipo_nivel_federativo_nome,a.Protocolo pedidos_protocolo,a.Titulo pedidos_titulo,a.Slug pedidos_slug,a.Descricao pedidos_descricao,"" pedidos_enviado_para,DATE_FORMAT(a.DataEnvio,"%Y-%m-%d") pedidos_data_envio,a.FoiProrrogado pedidos_foi_prorrogado,a.Anonimo pedidos_anonimo,case when b.Codigo is null Then 0 Else 1 end JaEnviado from pedidos a join pedidos_interacoes pi on a.Codigo = pi.CodigoPedido join pedidos_anexos pa on pa.CodigoPedidoInteracao = pi.Codigo left join es_pedidos_anexos b on pa.Codigo = b.CodigoPedidoAnexo join usuarios c on a.CodigoUsuario = c.Codigo join agentes d on d.Codigo = a.CodigoAgente join status_pedido e on a.CodigoStatusPedido = e.Codigo join status_pedido f on a.CodigoStatusPedidoInterno = f.Codigo join tipo_pedido_situacao g on g.Codigo = a.CodigoTipoPedidoSituacao join tipo_pedido_origem h on a.CodigoTipoOrigem = h.Codigo join tipo_poder tp on tp.Codigo = d.CodigoPoder join tipo_nivel_federativo tnf on tnf.Codigo = d.CodigoNivelFederativo join tipo_pedido_resposta tpr on tpr.Codigo = pi.CodigoTipoPedidoResposta join moderacoes modera on modera.CodigoObjeto = a.Codigo and modera.CodigoTipoObjeto = 1 and modera.CodigoStatusModeracao = 2 where a.Ativo = 1 and b.Codigo is null;
````

Tempo de execução: > 1 minuto

**Solução**
Melhorar a performance do banco (se possível) e da query

1. Mapear as tabelas / relacionamentos / campos com gargalo e criar índices
2. Verificar configurações do banco de dados e fazer algumas configurações como aumentar o buffer 
3. Ver se conseguimos melhorar algo da query

**Anexos:**
Documentação da API: https://endp.achadosepedidos.org.br/doc-api/

**Comment by rdurl0** [comment]
Olhando somente a sintaxe da query, tenho algumas dúvidas:

1. O `Codigo` da tabela `es_pedidos_anexos` é recodificado com o `case when` e depois filtrado em um `where`: 
```mysql
  case when b.Codigo is null Then 0 Else 1 end JaEnviado 
  (...)
  where a.Ativo = 1 and b.Codigo is null
```

2. A tabela `status_pedido` faz 2 joins, me parece uma operação redundante:
```mysql
join status_pedido e on a.CodigoStatusPedido = e.Codigo
join status_pedido f on a.CodigoStatusPedidoInterno = f.Codigo
```

3. O comando `join` é qual tipo de operação, exatamente? Seria análogo à um `cross join` ou `inner join`? ([referência](https://learnsql.com/blog/sql-joins/)). Pergunto pois a relação entre `pedidos_interacoes` e `pedidos_anexos` é do tipo muitos-para-muitos.

**Comment by studiocuboweb** [comment]
@rdurl0 vamos la:

0. Query retorna vazia.
reposta: Sim, está retornando vazia porque não existem anexos para sincronizar no ES. Mesmo assim, ela leva mais d 1 minuto para retornar algo, no caso atual: Empty set (1 min 16.47 sec)
Você também notou esse tempo ou foi mais rápido?

2. A tabela status_pedido faz 2 joins, me parece uma operação redundante:
resposta: O campo CodigoStatusPedido é a avaliação feita pela pessoa que publicou o pedido, já o campo CodigoStatusPedidoInterno é a avaliação interna da TB. Dito isso, a afirmação está redundante ainda é valida ou podemos otimizar isso?

3. O comando join significa INNER JOIN

Sobre os itens 1 e 4 vc conseguiria reescrever essa query para testarmos a performance? Definitivamente me parecem pertinentes seus comentários. Me ajuda com isso?

**Comment by studiocuboweb** [comment]
@rdurl0 (cc @talitalobo) Essa query possui 3 funções principais:

**1. Verificar se um anexo ainda não foi sincronizado no elasticsearch através desse join:**
````
join es_pedidos_anexos b on pa.Codigo = b.CodigoPedidoAnexo 
````
e dessa condição:
````
b.Codigo is null;
````

Se o anexo existe na tabela pedidos_anexos, mas não existe no es_pedidos_anexos, significa que ele não está no elasticsearch e deve ser adicionado na lista de sincronização (que é um loop da base com chamada para a API que grava no elasticsearch)
````
$resultado_da_query =  "SELECT..."

loop $resultado_da_query as item

- PUT endp.achadosepedidos.org.br/api/anexos/gravar/item[$CODIGO_PEDIDO_ANEXO] (envia todos os campos da query)

endloop
````

**2. Pegar os metadados que vão ser gravados no elasticsearch**
Exemplo de anexo no elasticsearch: https://endp.achadosepedidos.org.br/api/anexos/consultar/158816

O json retornado no [endpoint]( https://endp.achadosepedidos.org.br/api/anexos/consultar/158816)  possui vários dados de pedidos, pedidos_interacoes e pedidos_anexos (principalmente o título e o texto). Então para os metadados, além das consultas na tabela pedidos, pedidos_interacoes e pedidos_anexos nós temos os outros joins das tabelas auxiliares que retornam os nomes para as foreign keys nas tabelas pedidos, pedidos_interacoes e pedidos_anexos.

**3. Verificar se o pedido já foi moderado**
````
join moderacoes modera on modera.CodigoObjeto = a.Codigo and modera.CodigoTipoObjeto = 1 and modera.CodigoStatusModeracao = 2 
````

Tendo essa explicação como base, testei os ajustes que você me passou, mas não reduziu o tempo de execução da query. Posso eliminar todos os joins das tabelas auxiliares que a query vai continuar com mais de 1 minuto de execução... 

O gargalo está nos joins das tabelas grandes entre pedidos, pedidos_interacoes, pedidos_anexos e es_pedidos_anexos. Na query abaixo eu deixei apenas o "core" e a query levou 1m 25s de execução

````
Select 
    pa.Codigo anexos_codigo, 
    pa.Arquivo anexos_arquivo, 
    "" anexos_conteudo_arquivo, 
    pi.Codigo interacoes_codigo, 
    pi.Descricao interacoes_descricao, 
    DATE_FORMAT(pi.DataResposta,"%Y-%m-%d") interacoes_data_resposta,
    a.Codigo pedidos_codigo,a.CodigoUsuario usuarios_codigo,
    a.Protocolo pedidos_protocolo,
    a.Titulo pedidos_titulo,
    a.Slug pedidos_slug,
    a.Descricao pedidos_descricao,
    "" pedidos_enviado_para,
    DATE_FORMAT(a.DataEnvio,"%Y-%m-%d") pedidos_data_envio,
    a.FoiProrrogado pedidos_foi_prorrogado,
    a.CodigoTipoPedidoSituacao tipo_pedido_situacao_codigo,
    a.CodigoStatusPedido status_pedido_codigo,
    case when b.Codigo is null Then 0 Else 1 end JaEnviado 
    from pedidos a 
        join pedidos_interacoes pi on a.Codigo = pi.CodigoPedido 
        join pedidos_anexos pa on pa.CodigoPedidoInteracao = pi.Codigo left 
        join es_pedidos_anexos b on pa.Codigo = b.CodigoPedidoAnexo
        join moderacoes modera on modera.CodigoObjeto = a.Codigo and modera.CodigoTipoObjeto = 1 and modera.CodigoStatusModeracao = 2 
    where a.Ativo = 1 and b.Codigo is null;
````


Alguma sugestão de como reescrever essa lógica?

**Comment by studiocuboweb** [comment]
@rdurl0 @talitalobo Desculpem pelos disparos consecutivos  de emails rs

Só para avisar que consegui melhorar a query e foi necessário criar uma view.
[Nesse pull request](https://github.com/Transparencia-Brasil/achados-e-pedidos-site/pull/65/files) tem o código da view e a alteração que eu fiz no código para contemplar a nova query.

Está atualizado no [stage](https://stage.achadosepedidos.org.br/minhaconta/login/logar) para validação de vocês.
Agora está levando em torno dos 14 segundos para completar o cadastro de toda a resposta com o documento em anexo.

O fluxo de teste está descrito no primeiro post dessa tread.
Incluir a parte de moderação neste fluxo, blz?

Vale lembrar que a base de dados e o elastic search estão em ambiente de produção.

Fico no aguardo da validação de vocês. Qq dúvida é só chamar

Segue a query na integra: Tem alguma coisa para acrescen / melhorar pessoal?
```
SELECT 
    paesview.*,
    "" anexos_conteudo_arquivo, 
    pi.Descricao interacoes_descricao, 
    DATE_FORMAT(pi.DataResposta,"%Y-%m-%d") interacoes_data_resposta,
    c.Nome usuarios_nome,
    c.Nome usuarios_slug,
    c.Email usuarios_email,
    d.Codigo agentes_codigo,
    d.Nome agentes_nome,
    d.Nome agentes_slug,
    h.Codigo tipo_pedido_origem_codigo,
    h.Nome tipo_pedido_origem_nome,
    g.Nome tipo_pedido_situacao_nome,
    e.Nome status_pedido_nome,
    f.Codigo status_pedido_interno_codigo,
    f.Nome status_pedido_interno_nome,
    tpr.Codigo tipo_pedidos_resposta_codigo,
    tpr.Nome tipo_pedido_origem_nome,
    tp.Codigo tipo_poder_codigo,
    tp.Nome tipo_poder_nome,
    tnf.Codigo tipo_nivel_federativo_codigo,
    tnf.Nome tipo_nivel_federativo_nome,
    p.Protocolo pedidos_protocolo,
    p.Titulo pedidos_titulo,
    p.Slug pedidos_slug,
    p.Descricao pedidos_descricao,
    "" pedidos_enviado_para,
    DATE_FORMAT(p.DataEnvio,"%Y-%m-%d") pedidos_data_envio,
    p.FoiProrrogado pedidos_foi_prorrogado,
    p.Anonimo pedidos_anonimo
FROM 
    pedidosAnexosElasticSearchView as paesview
LEFT JOIN pedidos as p ON p.Codigo =  paesview.pedidos_codigo
LEFT JOIN pedidos_interacoes as pi ON pi.CodigoPedido = p.Codigo
LEFT JOIN usuarios c on p.CodigoUsuario = c.Codigo 
LEFT JOIN agentes d on d.Codigo = p.CodigoAgente 
LEFT JOIN status_pedido e on p.CodigoStatusPedido = e.Codigo 
LEFT JOIN status_pedido f on p.CodigoStatusPedidoInterno = f.Codigo 
LEFT JOIN tipo_pedido_situacao g on g.Codigo = p.CodigoTipoPedidoSituacao 
LEFT JOIN tipo_pedido_origem h on p.CodigoTipoOrigem = h.Codigo 
LEFT JOIN tipo_poder tp on tp.Codigo = d.CodigoPoder 
LEFT JOIN tipo_nivel_federativo tnf on tnf.Codigo = d.CodigoNivelFederativo 
LEFT JOIN tipo_pedido_resposta tpr on tpr.Codigo = pi.CodigoTipoPedidoResposta;
```

**Comment by rdurl0** [comment]
Oi, @studiocuboweb Paulo

Fiz o teste no stage. Tentando reproduzir os pedidos relatados na issue #66 e, de fato, o processo de upload me pareceu mais celere. Entretanto o problema relatado na issue #66 persiste, sugerindo que não são problemas relacionados.

Repare nas imagens que seleciono 5 arquivos e somente 4 entram no pedido. Depois eu faço uma edição do pedido reinserindo o arquivo que não subiu e aparece uma notificação de que o "Pedido foi atualizado com sucesso", mas o anexo continua não carregando no pedido.

![image](https://user-images.githubusercontent.com/22898231/216177958-885f5136-5e17-4bdc-a095-8f17d3cf5738.png)

![image](https://user-images.githubusercontent.com/22898231/216178065-8be5622c-58a4-4e42-8362-3b272f2445cf.png)

![image](https://user-images.githubusercontent.com/22898231/216178363-4b521bbe-64a8-4aab-8f70-56ecba10871c.png)

![image](https://user-images.githubusercontent.com/22898231/216178625-fd33eeb1-60b5-4fd0-977d-b625a4050383.png)
