### ISSUE TITLE
Problema no captcha no fluxo de cadastro de um usuário

### ISSUE THREAD

**Issue by studiocuboweb** [Transparencia-Brasil/achados-e-pedidos-site#8]
**Descrição:**

[No cadastro de um novo usuário](http://transparencia-achados.azurewebsites.net/cadastro) o captcha não está funcionando. Sempre que digitar as palavras e submeter o cadastro, volta um erro que o captcha está invalido, mesmo estando correto.

**Problema:**

O problema acontece porque o captcha não está atualizando a variável de sessão com o desafio correto.
Ao entrar na página é gerado um desafio ex: xptos que é gravado na sessão, mas a imagem mostra um outro desafio ex: ttypo. Ao digitar ttypo ele compara com xptos e retorna captcha invalido.

**Solução:**

Tiramos o captcha do cadastro.

**Teste:**

Entrar na [página de cadastro ](http://transparencia-achados.azurewebsites.net/cadastro) e concluir um cadastro até o fim.

**Pull Request:**

https://github.com/Transparencia-Brasil/achados-e-pedidos-site/pull/9

**Ticket:** 

https://trello.com/c/LWncwgHT/158-158-migracao-azure-aep-problema-no-captcha

**Comment by studiocuboweb** [comment]
@rdurl0 @JnCoe @mgaldino 
Captcha retirado do fluxo de cadastro. Favor testar.

Se estiver tudo certo, pode fechar o issue.

**Comment by maiatoji** [comment]
Tudo certo.
